spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hj_prod
    username: hj_prod_user
    password: hjpwd
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
